# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ib1CguR7rKCGrdlSZ175ts8TzCQKFz21
"""



class aluno:
  def __int__(self, matricula, nome, nota1, nota2, trabalho):
    self.matricula = matricula
    self.nome = nome
    self.nota1 = nota1
    self.nota2 = nota2
    self.trabalho = trabalho
  
  def resultado(self):
    media = (self.nota1 + self.nota2 + self.trabalho) / 3
    if media <4.0:
      return "reprovado"
    elif media <=7.0:
      return "aprovado"
    else:
      return f"final: (10.0 - media:.2f)"